import os, json
ROOT=os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..'))
WF='W/features/'; AF='A/features/'
def F(app, group, name, url, desc, entry=(), comp=(), load=(), svc=(), repo=(), pkg=()):
    return dict(app=app, group=group, name=name, url=url, desc=desc, entry=list(entry), comp=list(comp), load=list(load), svc=list(svc), repo=list(repo), pkg=list(pkg))
G1='公開サイト：議案を読む'; G2='公開サイト：AIチャット'; G3='公開サイト：インタビュー'; G4='公開サイト：意見とトピック'; G5='公開サイト：オープンデータ・連携'
H1='管理画面：ログイン・管理者'; H2='管理画面：議案'; H3='管理画面：インタビュー'; H4='管理画面：トピック分析'; H5='管理画面：外部連携'
M='W/app/(main)/'; AM='A/app/(protected)/'
FEATURES=[
F('web',G1,'トップページ','/', '注目の議案、インタビュー受付中の議案、タグ別・会期別の議案、トップのAIチャットをまとめて出す',
  [M+'page.tsx'],
  [WF+'bills/server/components/featured-bill-section.tsx',WF+'bills/server/components/interview-open-bill-section.tsx',WF+'bills/server/components/bills-by-tag-section.tsx',WF+'bills/server/components/previous-session-section.tsx',WF+'bills/server/components/past-session-list.tsx',WF+'diet-sessions/client/components/current-diet-session.tsx',WF+'chat/client/components/home-chat-client.tsx'],
  [WF+'bills/server/loaders/load-home-data.ts',WF+'bills/server/loaders/get-featured-bills.ts',WF+'bills/server/loaders/get-bills-by-featured-tags.ts',WF+'bills/server/loaders/get-interview-open-bills.ts',WF+'bills/server/loaders/get-coming-soon-bills.ts',WF+'diet-sessions/server/loaders/get-current-diet-session.ts',WF+'bills/server/loaders/get-past-sessions-with-bill-count.ts'],
  [WF+'bills/shared/utils/pick-home-sections.ts'],
  [WF+'bills/server/repositories/bill-repository.ts',WF+'diet-sessions/server/repositories/diet-session-repository.ts']),
F('web',G1,'議案一覧・絞りこみ・並べ替え','/bills','状態・タグでの絞りこみ、キーワード検索、並べ替え、インタビュー件数の表示',
  [M+'bills/page.tsx'],
  [WF+'bills/server/components/bills-list-page.tsx',WF+'bills/client/components/bill-list/bills-sort-select.tsx',WF+'bills/client/components/bill-search-overlay.tsx'],
  [WF+'bills/server/loaders/get-bills.ts',WF+'bills/server/loaders/get-bills-with-report-counts.ts',WF+'bills/server/loaders/get-featured-tags.ts'],
  [WF+'bills/shared/utils/parse-bills-list-params.ts',WF+'bills/shared/utils/filter-bills.ts',WF+'bills/shared/utils/sort-bills.ts',WF+'bills/shared/utils/search-bills.ts'],
  [WF+'bills/server/repositories/bill-repository.ts'],
  ['P/shared/src/report-publication/count-public-reports.ts']),
F('web',G1,'会期ごとの議案','/kokkai/[slug]/bills','国会の会期（例：第219回）ごとに議案を状態別に並べる',
  [M+'kokkai/[slug]/bills/page.tsx'],
  [WF+'diet-sessions/client/components/diet-session-bill-list.tsx',WF+'diet-sessions/client/components/bill-list-with-status-filter.tsx'],
  [WF+'diet-sessions/server/loaders/get-diet-session-by-slug.ts',WF+'bills/server/loaders/get-bills-by-diet-session.ts'],
  [WF+'diet-sessions/shared/utils/format-session-period.ts'],
  [WF+'diet-sessions/server/repositories/diet-session-repository.ts',WF+'bills/server/repositories/bill-repository.ts']),
F('web',G1,'議案の詳細','/bills/[id]','解説本文・審議の進み具合・チームみらいの賛否・インタビューへの導線・意見のトピック',
  [M+'bills/[id]/page.tsx'],
  [WF+'bills/server/components/bill-detail/bill-detail-layout.tsx',WF+'bills/server/components/bill-detail/bill-content.tsx',WF+'bills/client/components/bill-detail/mirai-stance-card.tsx',WF+'bills/client/components/bill-detail/bill-status-progress.tsx',WF+'user-topic-analysis/server/components/bill-topics-preview-section.tsx'],
  [WF+'bills/server/loaders/get-bill-by-id.ts',WF+'bills/server/loaders/helpers/get-bill-content.ts',WF+'interview-report/server/loaders/get-public-reports-by-bill-id.ts',WF+'user-topic-analysis/server/loaders/get-public-topic-analysis.ts'],
  [WF+'bills/shared/utils/hide-unpublished-stance.ts',WF+'bills/shared/utils/bill-progress.ts'],
  [WF+'bills/server/repositories/bill-repository.ts',WF+'interview-report/server/repositories/interview-report-repository.ts'],
  ['P/shared/src/mirai-stance/publish-schedule.ts','P/shared/src/mirai-stance/reason-format.ts']),
F('web',G1,'むずかしさの切り替え','?difficulty=normal|hard','解説を「ふつう」「くわしく」で切り替える。選んだ値は Cookie に保存',
  ['W/middleware.ts'],
  [WF+'bill-difficulty/client/components/difficulty-selector.tsx'],
  [WF+'bill-difficulty/server/actions/set-difficulty-level.ts',WF+'bill-difficulty/server/loaders/get-difficulty-level.ts'],
  [WF+'bill-difficulty/server/services/set-difficulty-level-core.ts',WF+'bill-difficulty/shared/utils/parse-difficulty-level.ts'],
  [],[]),
F('web',G1,'ふりがな表示','（全ページ）','漢字にふりがなを付けるかどうかの切り替え。設定はブラウザに保存',
  [],
  ['W/lib/rubyful/ruby-toggle.tsx','W/lib/rubyful/initializer.tsx','W/lib/rubyful/manual-ruby.tsx'],
  [],
  ['W/lib/rubyful/index.ts','W/lib/rubyful/storage.ts','W/lib/rubyful/use-ruby-toggle.ts'],[],[]),
F('web',G1,'議案のシェア','/bills/[id]','X などへのシェアボタンと、シェア用の画像・文面',
  [],
  [WF+'bills/server/components/share/bill-share-buttons.tsx',WF+'bills/client/components/share/bill-share-modal.tsx'],
  [],
  [WF+'bills/client/utils/share-handlers.ts',WF+'bills/shared/utils/bill-share-image.ts'],[],[]),
F('web',G1,'公開前のプレビュー','/preview/bills/[id]?token=…','admin が発行したトークンがあるときだけ、下書きの議案やインタビューを見られる',
  [M+'preview/bills/[id]/page.tsx',M+'preview/bills/[id]/interview/page.tsx'],
  [],
  [WF+'bills/server/loaders/validate-preview-token.ts',WF+'bills/server/loaders/get-bill-by-id-admin.ts',WF+'interview-config/server/loaders/get-interview-config-admin.ts'],
  [WF+'interview-config/shared/utils/interview-links.ts'],
  [WF+'bills/server/repositories/bill-repository.ts'],[]),
F('web',G2,'AIチャット（議案・トップ）','POST /api/chat','議案の内容をもとに AI が答える。1人あたり・全体の1日の利用額に上限あり。必要ならインタビューを提案',
  ['W/app/api/chat/route.ts'],
  [WF+'chat/client/components/chat-window.tsx',WF+'chat/client/components/chat-button.tsx',WF+'chat/client/components/mobile-chat-dialog.tsx',WF+'chat/client/hooks/use-anonymous-supabase-user.ts'],
  [],
  [WF+'chat/server/services/handle-chat-request.ts',WF+'chat/server/services/cost-tracker.ts',WF+'chat/server/services/system-cost-guard.ts',WF+'chat/shared/utils/pick-chat-knowledge-source.ts','W/lib/prompt/index.ts'],
  [WF+'chat/server/repositories/chat-usage-repository.ts',WF+'bills/server/repositories/bill-repository.ts'],
  ['P/shared/src/ai/models.ts']),
F('web',G3,'インタビューの入口','/bills/[id]/interview','インタビューの説明と同意。途中のセッションがあれば再開、終わったものはレポートへ',
  [M+'bills/[id]/interview/page.tsx'],
  [WF+'interview-config/client/components/interview-lp-page.tsx',WF+'interview-config/client/components/interview-consent-modal.tsx'],
  [WF+'interview-config/server/loaders/get-interview-config.ts',WF+'interview-session/server/loaders/get-latest-interview-session.ts',WF+'interview-report/server/loaders/get-user-reports-by-interview-config.ts',WF+'interview-session/server/actions/archive-interview-session.ts'],
  [WF+'interview-config/shared/utils/format-estimated-duration.ts'],
  [WF+'interview-config/server/repositories/interview-config-repository.ts',WF+'interview-session/server/repositories/interview-session-repository.ts'],[]),
F('web',G3,'質問内容の開示','/bills/[id]/interview/disclosure','AI に渡している質問やプロンプトの方針を公開するページ',
  [M+'bills/[id]/interview/disclosure/page.tsx'],
  [WF+'interview-config/server/components/interview-disclosure-page.tsx'],
  [WF+'interview-config/server/loaders/load-disclosure-data.ts',WF+'interview-config/server/loaders/get-interview-questions.ts'],
  [],
  [WF+'interview-config/server/repositories/interview-config-repository.ts'],
  ['P/shared/src/interview-prompts/sections.ts']),
F('web',G3,'インタビューのチャット','/bills/[id]/interview/chat ・ POST /api/interview/chat','AI が質問し、回答を保存しながら会話を進める。3つのモード（bulk / loop / targeted）で質問の進め方が変わる',
  [M+'bills/[id]/interview/chat/page.tsx','W/app/api/interview/chat/route.ts'],
  [WF+'interview-session/client/components/interview-chat-client.tsx',WF+'interview-session/client/hooks/use-interview-chat.ts',WF+'interview-session/client/utils/interview-api-client.ts',WF+'interview-session/client/components/quick-reply-buttons.tsx'],
  [WF+'interview-session/server/loaders/initialize-interview-chat.ts',WF+'interview-session/server/actions/create-interview-session.ts'],
  [WF+'interview-session/server/services/handle-interview-chat-request.ts',WF+'interview-session/server/services/generate-initial-question.ts',WF+'interview-session/server/services/save-interview-message.ts',WF+'interview-session/server/utils/interview-logic.ts',WF+'interview-session/server/utils/build-interview-system-prompt.ts',WF+'interview-session/shared/utils/interview-logic/loop-mode.ts'],
  [WF+'interview-session/server/repositories/interview-session-repository.ts',WF+'chat/server/repositories/chat-usage-repository.ts'],
  ['P/shared/src/interview-prompts/common-sections.ts','P/shared/src/interview-prompts/loop-mode.ts','P/shared/src/interview-prompts/summary.ts']),
F('web',G3,'インタビューの完了とレポート作成','POST /api/interview/complete','会話からレポートを取り出し、AI で不適切な内容をチェックして保存。意見は1件ずつ interview_opinion にも入れる',
  ['W/app/api/interview/complete/route.ts'],
  [WF+'interview-session/client/hooks/use-interview-completion.ts',WF+'interview-session/client/components/interview-summary.tsx'],
  [],
  [WF+'interview-session/server/services/complete-interview-session.ts',WF+'interview-session/server/services/evaluate-moderation-score.ts',WF+'interview-session/server/utils/verify-session-ownership.ts',WF+'interview-session/shared/utils/report-extraction.ts'],
  [WF+'interview-session/server/repositories/interview-session-repository.ts'],
  ['P/shared/src/interview-report/sync-opinions.ts','P/shared/src/interview-report/build-opinion-rows.ts','P/shared/src/moderation/build-moderation-prompt.ts']),
F('web',G3,'インタビューの評価・感想','（チャット画面内）','星の評価と「質問が多すぎた」などのフィードバック',
  [],
  [WF+'interview-session/client/components/interview-rating-widget.tsx',WF+'interview-session/client/hooks/use-interview-rating.ts'],
  [WF+'interview-session/server/actions/submit-interview-rating.ts',WF+'interview-session/server/actions/submit-interview-feedback.ts'],
  [WF+'interview-session/shared/constants/feedback-tags.ts'],
  [WF+'interview-session/server/repositories/interview-session-repository.ts'],[]),
F('web',G3,'レポート完了画面・公開設定','/report/[reportId]/complete','自分のレポートを公開するか選ぶ。専門家として登録もできる',
  [M+'report/[reportId]/complete/page.tsx'],
  [WF+'interview-report/server/components/report-complete-page.tsx',WF+'interview-report/client/components/public-status-section.tsx',WF+'interview-report/client/components/make-public-modal.tsx',WF+'interview-report/client/components/expert-registration-section.tsx'],
  [WF+'interview-report/server/loaders/get-interview-report-by-id.ts',WF+'interview-report/server/actions/update-public-setting.ts',WF+'interview-report/server/actions/register-expert.ts',WF+'interview-report/server/loaders/get-expert-registration-status.ts'],
  [WF+'interview-report/shared/utils/expert-registration-validation.ts'],
  [WF+'interview-report/server/repositories/interview-report-repository.ts',WF+'interview-report/server/repositories/expert-registration-repository.ts'],[]),
F('web',G3,'公開レポートとリアクション','/report/[reportId]','公開されたレポートの表示と「参考になった」ボタン',
  [M+'report/[reportId]/page.tsx'],
  [WF+'interview-report/server/components/public-report-page.tsx',WF+'report-reaction/client/components/reaction-buttons.tsx',WF+'report-reaction/client/hooks/use-reaction-toggle.ts'],
  [WF+'interview-report/server/loaders/get-public-report-by-id.ts',WF+'report-reaction/server/loaders/get-report-reactions.ts',WF+'report-reaction/server/actions/toggle-reaction.ts'],
  [WF+'report-reaction/shared/utils/compute-optimistic-state.ts',WF+'interview-report/shared/utils/public-report-display.ts'],
  [WF+'interview-report/server/repositories/interview-report-repository.ts',WF+'report-reaction/server/repositories/report-reaction-repository.ts'],
  ['P/shared/src/report-publication/auto-publish.ts']),
F('web',G4,'みんなの意見（回答者一覧）','/bills/[id]/opinions','公開されたインタビューの回答者と意見を一覧にする',
  [M+'bills/[id]/opinions/page.tsx'],
  [WF+'user-topic-analysis/server/components/bill-opinions-page.tsx',WF+'user-topic-analysis/client/components/respondent-list.tsx'],
  [WF+'user-topic-analysis/server/loaders/get-public-bill-respondents.ts'],
  [WF+'user-topic-analysis/shared/utils/count-respondents.ts'],
  [],
  ['P/topic-analysis-core/src/public/loaders.ts','P/topic-analysis-core/src/public/build-public-bill-respondents.ts','P/topic-analysis-core/src/public/public-read-repository.ts']),
F('web',G4,'意見のトピック一覧・詳細','/bills/[id]/topics ・ /topics/[topicId]','AI が意見をトピックごとにまとめた結果（公開済みの版だけ）を出す',
  [M+'bills/[id]/topics/page.tsx',M+'bills/[id]/topics/[topicId]/page.tsx','W/app/api/bills/[billId]/topic-analysis/route.ts'],
  [WF+'user-topic-analysis/server/components/topic-list-page.tsx',WF+'user-topic-analysis/server/components/topic-detail-page.tsx',WF+'user-topic-analysis/shared/components/topic-card.tsx'],
  [WF+'user-topic-analysis/server/loaders/get-public-topic-analysis.ts',WF+'user-topic-analysis/server/loaders/get-public-topic-detail.ts'],
  [WF+'user-topic-analysis/shared/utils/pick-card-quotes.ts',WF+'user-topic-analysis/shared/utils/filter-topics.ts'],
  [],
  ['P/topic-analysis-core/src/public/build-public-topic-analysis.ts','P/topic-analysis-core/src/public/public-read-repository.ts']),
F('web',G5,'オープンデータAPI','GET /api/open-data/bills ・ /bills/[billId] ・ /interviews','議案と公開インタビューを JSON で配る。IP ごとの回数制限とカーソル式のページ送り',
  ['W/app/api/open-data/bills/route.ts','W/app/api/open-data/bills/[billId]/route.ts','W/app/api/open-data/interviews/route.ts','W/app/(developers)/developers/open-data-api/page.tsx'],
  [WF+'open-data/client/components/open-data-api-reference.tsx'],
  [],
  [WF+'open-data/server/services/get-open-data-bills.ts',WF+'open-data/server/services/get-open-data-interviews.ts',WF+'open-data/server/utils/rate-limit-guard.ts',WF+'open-data/shared/utils/cursor.ts',WF+'open-data/shared/utils/to-open-data-bill.ts'],
  [WF+'open-data/server/repositories/open-data-repository.ts'],[]),
F('web',G5,'キャッシュの無効化（admin から呼ばれる）','POST /api/revalidate','admin が更新したとき、Bearer トークンつきで呼ばれ、タグ単位でキャッシュを消す',
  ['W/app/api/revalidate/route.ts'],[],[],['W/lib/cache-tags.ts'],[],[]),

F('admin',H1,'ログイン','/login ・ /api/auth/callback','メール＋パスワード、または Google ログイン。roles に admin がないと入れない',
  ['A/app/login/page.tsx','A/app/api/auth/callback/route.ts','A/middleware.ts'],
  [AF+'auth/client/components/login-form.tsx',AF+'auth/client/hooks/use-login.ts',AF+'auth/client/lib/auth-client.ts'],
  [],
  [AF+'auth/server/lib/auth-server.ts','A/lib/auth/permissions.ts'],[],[]),
F('admin',H1,'管理者の招待・削除','/admins','メールで管理者を招待、削除',
  [AM+'admins/page.tsx'],
  [AF+'admins/client/components/invite-admin-form.tsx',AF+'admins/server/components/admin-list.tsx'],
  [AF+'admins/server/loaders/load-admins.ts',AF+'admins/server/actions/invite-admin.ts',AF+'admins/server/actions/delete-admin.ts'],
  [AF+'admins/shared/utils/validate-email.ts'],
  [AF+'admins/server/repositories/admin-repository.ts'],[]),
F('admin',H2,'議案一覧（公開・複製・削除・プレビュー）','/bills','公開状態の切り替え、議案の複製と削除、プレビューURLの発行',
  [AM+'bills/page.tsx'],
  [AF+'bills/server/components/bill-list/bill-list.tsx',AF+'bills/client/components/bill-actions-menu/bill-actions-menu.tsx',AF+'bills/client/components/bill-list/preview-button.tsx'],
  [AF+'bills/server/loaders/get-bills.ts',AF+'bills/server/actions/update-publish-status.ts',AF+'bills/server/actions/duplicate-bill.ts',AF+'bills/server/actions/delete-bill.ts',AF+'bills/server/actions/generate-preview-url.ts'],
  [AF+'bills/server/services/preview-token-service.ts',AF+'bills/shared/utils/prepare-bill-for-duplication.ts'],
  [AF+'bills/server/repositories/bill-repository.ts'],[]),
F('admin',H2,'議案の作成・編集・タグ','/bills/new ・ /bills/[id]/edit','議案の基本情報、サムネイル画像、タグ。保存すると web のキャッシュを消す',
  [AM+'bills/new/page.tsx',AM+'bills/[id]/edit/page.tsx'],
  [AF+'bills-edit/client/components/bill-create-form.tsx',AF+'bills-edit/client/components/bill-edit-form.tsx',AF+'bills-edit/client/components/bill-tags-form.tsx',AF+'bills-edit/client/components/thumbnail-upload.tsx',AF+'bills-edit/client/lib/thumbnail-storage.ts'],
  [AF+'bills-edit/server/actions/create-bill.ts',AF+'bills-edit/server/actions/update-bill.ts',AF+'bills-edit/server/actions/update-bill-tags.ts',AF+'bills-edit/server/loaders/get-bill-by-id.ts'],
  [AF+'bills-edit/server/services/update-bill-with-side-effects.ts',AF+'bills-edit/shared/utils/should-auto-close-interview.ts','A/lib/utils/cache-invalidation.ts'],
  [AF+'bills-edit/server/repositories/bill-edit-repository.ts'],[]),
F('admin',H2,'チームみらいの賛否','/bills/[id]/edit（賛否フォーム）','賛成・反対などの立場、判断の理由、補足情報、公開日時の予約',
  [],
  [AF+'mirai-stance/client/components/stance-form.tsx',AF+'mirai-stance/client/components/reason-new-format-fields.tsx'],
  [AF+'mirai-stance/server/loaders/get-stance-by-bill-id.ts',AF+'mirai-stance/server/actions/create-stance.ts',AF+'mirai-stance/server/actions/update-stance.ts',AF+'mirai-stance/server/actions/delete-stance.ts'],
  [AF+'mirai-stance/shared/utils/to-stance-columns.ts',AF+'mirai-stance/shared/utils/publish-at-input.ts'],
  [AF+'mirai-stance/server/repositories/mirai-stance-repository.ts'],
  ['P/shared/src/mirai-stance/publish-schedule.ts','P/shared/src/mirai-stance/reason-format.ts']),
F('admin',H2,'解説本文（ふつう・くわしく）','/bills/[id]/contents/edit','むずかしさごとのタイトル・要約・本文（Markdown）',
  [AM+'bills/[id]/contents/edit/page.tsx'],
  [AF+'bills-edit/client/components/bill-contents-edit-form.tsx'],
  [AF+'bills-edit/server/loaders/get-bill-contents.ts',AF+'bills-edit/server/actions/update-bill-contents.ts'],
  [],
  [AF+'bills-edit/server/repositories/bill-edit-repository.ts'],[]),
F('admin',H2,'会期・タグ','/diet-sessions ・ /tags','国会の会期（期間・スラッグ・現在の会期）とタグの管理',
  [AM+'diet-sessions/page.tsx',AM+'tags/page.tsx'],
  [AF+'diet-sessions/client/components/diet-session-form.tsx',AF+'tags/client/components/tag-form.tsx'],
  [AF+'diet-sessions/server/actions/create-diet-session.ts',AF+'diet-sessions/server/actions/set-active-diet-session.ts',AF+'tags/server/actions/create-tag.ts',AF+'tags/server/loaders/load-tags.ts'],
  [AF+'diet-sessions/shared/utils/validate-slug.ts',AF+'tags/shared/utils/map-tag-db-error.ts'],
  [AF+'diet-sessions/server/repositories/diet-session-repository.ts',AF+'tags/server/repositories/tag-repository.ts'],[]),
F('admin',H3,'インタビュー設定と質問','/bills/[id]/interview ・ /new ・ /[configId]/edit','モード、使う AI モデル、目安時間、質問と追加質問の方針、プロンプトの上書き',
  [AM+'bills/[id]/interview/page.tsx',AM+'bills/[id]/interview/[configId]/edit/page.tsx'],
  [AF+'interview-config/client/components/interview-config-edit-client.tsx',AF+'interview-config/client/components/interview-config-form.tsx',AF+'interview-config/client/components/interview-question-list.tsx'],
  [AF+'interview-config/server/loaders/get-interview-config.ts',AF+'interview-config/server/actions/upsert-interview-config.ts',AF+'interview-config/server/actions/save-interview-questions.ts',AF+'interview-config/server/actions/generate-interview-preview-url.ts'],
  [AF+'interview-config/shared/utils/estimate-interview-cost.ts',AF+'interview-config/shared/utils/default-questions-template.ts'],
  [AF+'interview-config/server/repositories/interview-config-repository.ts'],
  ['P/shared/src/interview-prompts/sections.ts']),
F('admin',H3,'AIでインタビュー設定を作る','POST /api/interview-config/generate','議案の本文をもとに、テーマや質問の案を AI と対話しながら作る',
  ['A/app/api/interview-config/generate/route.ts'],
  [AF+'interview-config/client/components/config-generation-chat.tsx',AF+'interview-config/client/hooks/use-config-generation-chat.ts'],
  [],
  [AF+'interview-config/server/services/handle-config-generation.ts',AF+'interview-config/server/utils/build-config-generation-prompt.ts'],
  [AF+'bills-edit/server/repositories/bill-edit-repository.ts'],
  ['P/shared/src/stream/inject-json-fields.ts']),
F('admin',H3,'インタビューのシミュレーション','POST /api/interview-simulation/run-multi','AI が回答者役（ペルソナ）を作って模擬インタビューし、満足度を採点する',
  ['A/app/api/interview-simulation/run-multi/route.ts'],
  [AF+'interview-simulation/client/components/multi-simulation-view.tsx',AF+'interview-simulation/client/hooks/use-multi-simulation-run.ts'],
  [AF+'interview-simulation/server/loaders/get-completed-reports-for-bill.ts'],
  [AF+'interview-simulation/server/services/run-multi-simulation-pipeline.ts',AF+'interview-simulation/server/services/generate-persona.ts',AF+'interview-simulation/server/services/run-simulated-interview.ts',AF+'interview-simulation/server/services/evaluate-interviewee-satisfaction.ts'],
  [AF+'interview-simulation/server/repositories/interview-simulation-repository.ts'],[]),
F('admin',H3,'レポート一覧・統計・TSV・一括公開','/bills/[id]/interview/[configId]/reports','並べ替え・絞りこみ、所要時間や回答数の統計、TSV 出力、条件に合うレポートの一括公開',
  [AM+'bills/[id]/interview/[configId]/reports/page.tsx'],
  [AF+'interview-reports/server/components/session-list.tsx',AF+'interview-reports/server/components/interview-statistics.tsx',AF+'interview-reports/client/components/batch-publish-button.tsx',AF+'interview-reports/client/components/copy-tsv-button.tsx'],
  [AF+'interview-reports/server/loaders/get-interview-sessions.ts',AF+'interview-reports/server/loaders/get-interview-statistics.ts',AF+'interview-reports/server/actions/bulk-publish-reports-action.ts',AF+'interview-reports/server/actions/export-interview-tsv-action.ts'],
  [AF+'interview-reports/shared/utils/parse-session-filter-params.ts',AF+'interview-reports/shared/utils/build-interview-tsv.ts'],
  [AF+'interview-reports/server/repositories/interview-report-repository.ts'],[]),
F('admin',H3,'レポート詳細・公開切替・再採点','/bills/[id]/interview/[configId]/reports/[sessionId]','会話ログ、公開／非公開の切り替え、モデレーションと内容の充実度の採点やり直し',
  [AM+'bills/[id]/interview/[configId]/reports/[sessionId]/page.tsx','A/app/api/batch/moderation-scoring/route.ts'],
  [AF+'interview-reports/server/components/session-detail.tsx',AF+'interview-reports/client/components/report-visibility-toggle.tsx',AF+'interview-reports/client/components/batch-moderation-button.tsx'],
  [AF+'interview-reports/server/loaders/get-interview-session-detail.ts',AF+'interview-reports/server/actions/update-report-visibility.ts',AF+'interview-reports/server/actions/run-single-moderation-action.ts',AF+'interview-reports/server/actions/run-single-content-richness-action.ts'],
  [AF+'interview-reports/server/services/batch-moderation-scoring.ts',AF+'interview-reports/server/services/content-richness-scoring.ts'],
  [AF+'interview-reports/server/repositories/interview-report-repository.ts'],
  ['P/shared/src/moderation/moderation.ts','P/shared/src/content-richness/build-content-richness-prompt.ts']),
F('admin',H3,'発言の検索・全インタビュー・専門家','/reports/search ・ /interviews ・ /experts','回答者の発言をキーワード検索、全議案のインタビュー設定一覧、専門家登録の一覧',
  [AM+'bills/[id]/interview/[configId]/reports/search/page.tsx',AM+'interviews/page.tsx',AM+'experts/page.tsx'],
  [AF+'interview-reports/client/components/message-search-form.tsx',AF+'interviews/server/components/all-interview-config-list.tsx',AF+'experts/server/components/expert-list.tsx'],
  [AF+'interview-reports/server/loaders/search-user-messages.ts',AF+'interviews/server/loaders/get-all-interview-configs.ts',AF+'experts/server/loaders/load-experts.ts'],
  [AF+'interview-reports/shared/utils/escape-ilike-pattern.ts'],
  [AF+'interview-reports/server/repositories/interview-report-repository.ts',AF+'experts/server/repositories/expert-repository.ts'],[]),
F('admin',H4,'トピック分析（Cloud Run で実行）','/bills/[id]/user-topic-analysis ・ /user-topic-analysis ・ POST /api/user-topic-analysis/dispatch','version を作って Cloud Run Job を起動。worker が意見の抽出 → 統合 → 割り当て → 2階層化を行い、終わると自動公開',
  [AM+'bills/[id]/user-topic-analysis/page.tsx',AM+'user-topic-analysis/page.tsx','A/app/api/user-topic-analysis/dispatch/route.ts','A/app/api/user-topic-analysis/dispatch-all/route.ts','A/app/api/user-topic-analysis/status/route.ts'],
  [AF+'user-topic-analysis/server/components/user-topic-analysis-page.tsx',AF+'user-topic-analysis/client/components/run-analysis-button.tsx',AF+'user-topic-analysis/client/components/publish-toggle-button.tsx'],
  [AF+'user-topic-analysis/server/actions/publish-actions.ts',AF+'user-topic-analysis/server/actions/delete-topic-actions.ts'],
  ['A/lib/cloud-run-job.ts','worker/src/main.ts','P/topic-analysis-core/src/analyze.ts','P/topic-analysis-core/src/services/extract-topics.ts','P/topic-analysis-core/src/services/assign-opinions.ts','P/topic-analysis-core/src/services/group-topics.ts'],
  ['P/topic-analysis-core/src/repositories/analysis-repository.ts'],
  ['P/topic-analysis-core/src/utils/incremental.ts']),
F('admin',H4,'意見の再抽出バックフィル','/interview-opinion-backfill ・ /api/interview-opinion-backfill/*','古いレポートから意見を取り出し直して interview_opinion に入れる（Cloud Run で実行）',
  [AM+'interview-opinion-backfill/page.tsx','A/app/api/interview-opinion-backfill/dispatch/route.ts','A/app/api/interview-opinion-backfill/status/route.ts'],
  [AF+'interview-opinion-backfill/client/components/opinion-backfill-runner.tsx'],
  [],
  ['P/topic-analysis-core/src/backfill.ts','P/topic-analysis-core/src/services/reextract-report-opinions.ts','P/topic-analysis-core/src/tag-backfill.ts'],
  ['P/topic-analysis-core/src/repositories/backfill-repository.ts'],[]),
F('admin',H4,'分析ビューア（マインドマップ）','/bills/[id]/analysis-viewer','トピックと意見の関係を、ノードと線の図で見る',
  [AM+'bills/[id]/analysis-viewer/page.tsx'],
  [AF+'analysis-viewer/server/components/analysis-viewer-page.tsx',AF+'analysis-viewer/client/components/topic-mindmap.tsx'],
  [AF+'analysis-viewer/server/loaders/get-analysis-for-viewer.ts'],
  [AF+'analysis-viewer/shared/utils/build-mindmap-graph.ts',AF+'analysis-viewer/shared/utils/build-viewer-hierarchy.ts'],
  [AF+'analysis-viewer/server/repositories/analysis-viewer-repository.ts'],[]),
F('admin',H4,'旧トピック分析（設定ごと・5ステップ）','/bills/[id]/interview/[configId]/topic-analysis ・ POST /api/topic-analysis/run','インタビュー設定ごとの分析。Vercel 上で phase1〜3 の API を順に呼び継いで実行する',
  [AM+'bills/[id]/interview/[configId]/topic-analysis/page.tsx','A/app/api/topic-analysis/run/route.ts','A/app/api/topic-analysis/phases/phase1/route.ts'],
  [AF+'topic-analysis/server/components/topic-analysis-page.tsx',AF+'topic-analysis/client/components/run-analysis-button.tsx'],
  [AF+'topic-analysis/server/actions/run-topic-analysis-action.ts',AF+'topic-analysis/server/loaders/get-topic-analysis-versions.ts'],
  [AF+'topic-analysis/server/services/topic-analysis-orchestrator.ts',AF+'topic-analysis/server/services/step1-extract-topics.ts',AF+'topic-analysis/server/services/step5-generate-summary.ts',AF+'topic-analysis/server/utils/trigger-next-phase.ts'],
  [AF+'topic-analysis/server/repositories/topic-analysis-repository.ts'],[]),
F('admin',H5,'MCPサーバー（AIエージェントから操作）','POST /api/mcp','Claude などの AI エージェントが、議案・賛否・タグ・統計などをツールとして読み書きする。Bearer トークンで認証',
  ['A/app/api/mcp/route.ts'],
  [],
  [],
  [AF+'mcp/server/create-handler.ts',AF+'mcp/server/verify-token.ts',AF+'mcp/server/tools/register-bills-tools.ts',AF+'mcp/server/tools/register-mirai-stance-tools.ts',AF+'mcp/server/tools/register-topic-analysis-tools.ts',AF+'mcp/server/utils/untrusted-json-result.ts'],
  [AF+'mcp/server/repositories/chat-usage-repository.ts'],
  ['P/shared/src/prompt-safety/untrusted-content.ts']),
]
def expand(p):
    return p.replace('W/','web/src/',1).replace('A/','admin/src/',1).replace('P/','packages/',1) if p[:2] in ('W/','A/','P/') else p
missing=[]
for f in FEATURES:
    for k in ['entry','comp','load','svc','repo','pkg']:
        f[k]=[expand(p) for p in f[k]]
        for p in f[k]:
            if not os.path.exists(os.path.join(ROOT,p)): missing.append((f['name'],p))
print('features',len(FEATURES)); print('missing',missing)
json.dump(FEATURES,open('features.json','w'),ensure_ascii=False)
